apiVersion: v2
publisher: fwcd
name: vscode-kotlin
version: 0.2.18
type: VS Code extension
displayName: Kotlin
title: Kotlin tooling for VS Code
description: This plug-in provides support for Kotlin development.
icon: https://raw.githubusercontent.com/JetBrains/logos/master/web/kotlin/kotlin.svg
repository: https://github.com/fwcd/vscode-kotlin/
category: Language
spec:
  containers:
    - image: "quay.io/bluesman/che-sidecar-maven:latest"
      name: vscode-kotlin
      memoryLimit: "5000Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
      - mountPath: "/home/theia/home/theia"
        name: vscode-theia-workaround
  extensions:
    - https://github.com/fwcd/vscode-kotlin/releases/download/0.2.18/kotlin-0.2.18.vsix
